# 应用基本信息  
spring:
  application:
    name: alist-admin

# Nacos配置  
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: public
    group: DEFAULT_GROUP
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: public

# 本地开发配置  
logging:
  level:
    org.AList: debug

# 本地备用配置  
server:
  port: 8888