server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alist
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1  # 确认是否是实际 Redis 地址
    port: 6379
    database: 2       # 确认选择的数据库
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
jwt:
  # 为JWT基础信息加密和解密的密钥，长度需要大于等于43
  # 在实际生产中通常不直接写在配置文件里面。而是通过应用的启动参数传递，并且需要定期修改
  secret: "VGhpcyBpcyBhIHNlY3JldCBrZXkhVGhpcyBpcyBhIHNlY3JldCBrZXkhVGhpcyBpcyBhIHNlY3JldCBrZXkhVGhpcyBpcyBhIHNlY3JldCBrZXkh"
  # JWT令牌的有效时间，单位秒，默认2周
  expiration: 1209600
  token: tk-auth