# 应用基本信息  
spring:
  application:
    name: alist-students

# Nacos配置（不使用Spring Cloud）  
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: public
    group: DEFAULT_GROUP
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: public

# 本地开发配置（作为备用）  
logging:
  level:
    org.AList: debug

# 本地备用配置（当Nacos不可用时使用）  
server:
  port: 7777